apiVersion: v1
kind: Service
metadata:
  name: nodejs-api
  labels:
    app: nodejs-api
spec:
  selector:
    app: nodejs-api
  type: NodePort             # Expose service externally
  ports:
    - protocol: TCP
      port: 3000             # Service port inside the cluster
      targetPort: 3000       # Container port
      nodePort: 32000        # Port exposed on the EC2 host
